CRITICAL - 2022-05-19 01:27:12 --> Use of undefined constant base_url - assumed 'base_url' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\FIMA\app\Views\ViewD\Dashboard.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('ViewD/Dashboard', Array, true)
#4 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(21): view('ViewD/Dashboard', Array)
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_dashboard()
#6 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#7 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-05-19 01:48:53 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::count_all_results()
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 01:49:22 --> Call to undefined method App\Models\RumusKPI::count_all_results
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(35): CodeIgniter\Model->__call('count_all_resul...', Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 02:51:57 --> print_r() expects at least 1 parameter, 0 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r() expec...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(41): print_r()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-19 04:35:04 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(55): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:38:07 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(56): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:42:49 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(56): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:42:56 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(56): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:43:01 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(56): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:44:19 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(56): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:45:57 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(64): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:46:31 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(64): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:52:52 --> Call to a member function getResultArray() on bool
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 04:53:49 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(63): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:54:51 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(63): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:54:53 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(63): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 04:55:14 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(63): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 11:00:23 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(63): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 11:02:51 --> There is no data to insert.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Model.php(686): CodeIgniter\BaseModel->insert(Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(64): CodeIgniter\Model->insert(Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 20:02:39 --> Class 'App\Controllers\ViewModel' not found
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 20:06:33 --> Class 'APP\Models\ViewKPIModel' not found
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 20:07:18 --> Class 'APP\Models\ViewKPIModel' not found
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 20:07:20 --> Class 'APP\Models\ViewKPIModel' not found
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 21:16:28 --> Too few arguments to function App\Controllers\ViewD::show_dashboard(), 0 passed in C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php on line 931 and exactly 1 expected
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_dashboard()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 21:25:55 --> Call to a member function getWhere() on null
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 21:28:47 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('ViewD/Dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:32:09 --> Invalid file: Dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Dashboard.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('Dashboard', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('Dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:34:54 --> Invalid file: Dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Dashboard.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('Dashboard', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('Dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:38:17 --> Invalid file: Dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Dashboard.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('Dashboard', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('Dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:42:29 --> Invalid file: ViewD::show_dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('ViewD::show_das...')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('ViewD::show_das...', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('ViewD::show_das...', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:42:48 --> Invalid file: show_dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('show_dashboard....')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('show_dashboard', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('show_dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:42:57 --> Invalid file: Dashboard.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Dashboard.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('Dashboard', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('Dashboard', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:43:20 --> Invalid file: KpiToTarget.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('KpiToTarget.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('KpiToTarget', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(20): view('KpiToTarget', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 21:45:11 --> Invalid file: KpiToTarget.php
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('KpiToTarget.php')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(1250): CodeIgniter\View\View->render('KpiToTarget', Array, true)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(20): view('KpiToTarget', Array)
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->show_kpi_to_target()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:30:51 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(93): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:31:17 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(93): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:31:44 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:31:54 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:32:00 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:32:13 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:32:27 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:32:39 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:38:01 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:38:19 --> Argument 2 passed to view() must be of the type array, string given, called in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 94
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): view('http://localhos...', 'refresh')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 22:38:52 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:39:03 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(94): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:42:35 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(91): redirect('DashboardArray')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:42:57 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(91): redirect('Dashboard/Array')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:43:59 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(91): redirect('show_dashboard/...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:44:36 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:45:07 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:45:14 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): redirect('http://localhos...')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:49:08 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): redirect('ViewD/Dashboard')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 22:53:32 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(64): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\Common.php(951): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): redirect('ViewD/Dashboard')
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#4 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#5 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-19 23:05:25 --> Argument 1 passed to CodeIgniter\HTTP\RedirectResponse::with() must be of the type string, array given, called in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with(Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 23:05:52 --> Argument 1 passed to CodeIgniter\HTTP\RedirectResponse::with() must be of the type string, array given, called in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with(Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 23:05:57 --> Argument 1 passed to CodeIgniter\HTTP\RedirectResponse::with() must be of the type string, array given, called in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with(Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 23:08:00 --> Too few arguments to function CodeIgniter\HTTP\RedirectResponse::with(), 1 passed in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90 and exactly 2 expected
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with('2022')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 23:08:46 --> Call to undefined function App\Controllers\to()
#0 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-19 23:09:10 --> Too few arguments to function CodeIgniter\HTTP\RedirectResponse::with(), 1 passed in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90 and exactly 2 expected
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with('2022')
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-19 23:19:27 --> Argument 1 passed to CodeIgniter\HTTP\RedirectResponse::with() must be of the type string, array given, called in C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php on line 90
#0 C:\xampp\htdocs\FIMA\app\Controllers\ViewD.php(90): CodeIgniter\HTTP\RedirectResponse->with(Array, Array)
#1 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(931): App\Controllers\ViewD->calculate_kpi()
#2 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(439): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ViewD))
#3 C:\xampp\htdocs\FIMA\vendor\codeigniter4\framework\system\CodeIgniter.php(339): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\FIMA\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
